[package]
name = "basil-stream-master"
version = "0.1.0"
authors = ["Bytekeeper <therealdante@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.11"
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"]}
rand = "0.7"
crossbeam-channel = "0.5"
actix-web-static-files = "3.0"
actix-web = "3"
actix-rt="1.1"

[build-dependencies]
actix-web-static-files = "3.0"
